//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPreferences
    {
        public int Id_ClientPreferences { get; set; }
        public Nullable<int> Id_Klient { get; set; }
        public string ClientPreferences1 { get; set; }
    
        public virtual Otzivi Otzivi { get; set; }
    }
}
