//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master()
        {
            this.Raspisanie = new HashSet<Raspisanie>();
        }
    
        public int Id_Mastera { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string SpecNazv { get; set; }
        public Nullable<int> Reyting { get; set; }
        public Nullable<int> Opit { get; set; }
        public string Skills { get; set; }
        public Nullable<int> Id_Uslugi { get; set; }
    
        public virtual Uslugi Uslugi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raspisanie> Raspisanie { get; set; }
    }
}
