//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages_Akcii
    {
        public int Id_Messages { get; set; }
        public Nullable<int> Id_Klienta { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
    
        public virtual Otzivi Otzivi { get; set; }
    }
}
