//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parikmaherEntities : DbContext
    {
        public parikmaherEntities()
            : base("name=parikmaherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akcii> Akcii { get; set; }
        public virtual DbSet<ClientPreferences> ClientPreferences { get; set; }
        public virtual DbSet<Kategorii_Uslug> Kategorii_Uslug { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Materiali> Materiali { get; set; }
        public virtual DbSet<Messages_Akcii> Messages_Akcii { get; set; }
        public virtual DbSet<Naviki> Naviki { get; set; }
        public virtual DbSet<Otzivi> Otzivi { get; set; }
        public virtual DbSet<Prodaji> Prodaji { get; set; }
        public virtual DbSet<Rashodi_Materialov> Rashodi_Materialov { get; set; }
        public virtual DbSet<Raspisanie> Raspisanie { get; set; }
        public virtual DbSet<Specializacii> Specializacii { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uslugi> Uslugi { get; set; }
        public virtual DbSet<Uvedi> Uvedi { get; set; }
        public virtual DbSet<Vipoln_Usligi> Vipoln_Usligi { get; set; }
        public virtual DbSet<Zapisi> Zapisi { get; set; }
        public virtual DbSet<Zarplati> Zarplati { get; set; }
    }
}
