//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rashodi_Materialov
    {
        public int Id_Rashodi_Materialov { get; set; }
        public Nullable<int> Id_Zapisi { get; set; }
        public Nullable<int> Id_Materiala { get; set; }
        public Nullable<int> Kolvo_Used { get; set; }
    
        public virtual Materiali Materiali { get; set; }
        public virtual Zapisi Zapisi { get; set; }
    }
}
