//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raspisanie
    {
        public int Id_Raspisanie { get; set; }
        public Nullable<int> Id_Mastera { get; set; }
        public Nullable<int> Rab_chasi { get; set; }
        public Nullable<int> Perev { get; set; }
    
        public virtual Master Master { get; set; }
    }
}
