//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uslugi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uslugi()
        {
            this.Master = new HashSet<Master>();
            this.Materiali = new HashSet<Materiali>();
            this.Prodaji = new HashSet<Prodaji>();
            this.Vipoln_Usligi = new HashSet<Vipoln_Usligi>();
            this.Zapisi = new HashSet<Zapisi>();
        }
    
        public int Id_Uslugi { get; set; }
        public string Nazvanie { get; set; }
        public Nullable<int> Kategoriya { get; set; }
        public Nullable<int> Stoimost { get; set; }
        public string Opisanie { get; set; }
        public Nullable<int> Dlitelnost_chasov { get; set; }
    
        public virtual Kategorii_Uslug Kategorii_Uslug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Master> Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiali> Materiali { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prodaji> Prodaji { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vipoln_Usligi> Vipoln_Usligi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zapisi> Zapisi { get; set; }
    }
}
