//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vipoln_Usligi
    {
        public int Id_Vipoln_Usligi { get; set; }
        public Nullable<int> Id_Klient { get; set; }
        public Nullable<int> Id_Uslugi { get; set; }
        public Nullable<System.DateTime> Дата_Выполнения { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
