//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zapisi()
        {
            this.Rashodi_Materialov = new HashSet<Rashodi_Materialov>();
        }
    
        public int Id_Zapisi { get; set; }
        public string Id_Sotrudnika { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Id_Uslugi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rashodi_Materialov> Rashodi_Materialov { get; set; }
        public virtual Uslugi Uslugi { get; set; }
    }
}
