//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.dbo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zarplati
    {
        public int Id_Zarp { get; set; }
        public Nullable<int> Id_Sotrudnika { get; set; }
        public Nullable<int> Zarplata { get; set; }
        public Nullable<int> Bonus { get; set; }
        public Nullable<int> Zarplata_Month { get; set; }
        public Nullable<int> Zarplata_Year { get; set; }
    }
}
